### ISSUE TITLE
Sugestão pra desempacar na produção

### ISSUE THREAD

**Issue by mkvlrn-cm42** [Hydeoshi/PIM#5]
São Judas Tadeu,
Glorioso Apóstolo,
Fiel servo e amigo de Jesus!
A Igreja vos honra e invoca por todo o mundo
como Patrono dos casos desesperados
e dos Negócios sem remédio.
Rogai por mim que estou desolado.
Eu vos imploro, fazei uso do privilégio
Que tendes de trazer socorro imediato,
Onde o socorro desapareceu quase que por completo.
Assiste-me nesta grande necessidade,
Para que eu possa receber as consoloações e auxílio
Do céu em todas as minhas precisões, tribulações e sofrimentos.
São Judas Tadeu, lembrar-me-ei sempre deste grande favor
E nunca deixarei de vos louvar e honrar como meu especial
E poderoso patrono
E fazer tudo que estiver ao meu alcance
Para espalhar a Vossa devoção por toda parte.

Amém…
São Judas Tadeu rogai por nós.

**Comment by klauss-m** [comment]
Amém.
